module.exports = {
    namalengkap: "janu akrama w",
    email: "januakramawardhana@gmail.com",
    pw: "Akram12345!",
    uname: "janu",
    notelp: "081386777480",
    cpw: "Akram12345!",
    JudulLaporan: "menghentikan covid-19",
    Laporan: "dalam sebuah restoran ada pengunjung yang diperbolehkan masuk tidak menggunakan masker, ini akan memperburuk keadaan dan melannggar protokol dengan nomor rumah B#A1122",
    AsalPelapor: "Kota : Bandung",
    InstansiTujuan: "Kepolisian Negara Republik Indonesia",
    KategoriLaporan: "Karantina Wilayah",
    lokasi: "Kota : Bandung",
    fieldJudulLaporanInformasi: "Bagaimana menghentikkan covid-19",
    fieldLaporanInformasi: "saya melihat laporan dari berita kasus covid-19 semakin naik, apalagi didaerah ibukota, bagaimana dari pihak pemerintah dalam pencegahan itu ?",
    InstansiTujuanFailed: "Kepolisian Negara Republik_Indonesia",
}
